#!/bin/bash

# Local Testing Setup Script for Torrorèndum 2025
# This script automates the local development setup

set -e

echo "🎯 Torrorèndum 2025 - Local Setup"
echo "================================="
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check prerequisites
echo "📋 Checking prerequisites..."

# Check Go
if ! command -v go &> /dev/null; then
    echo -e "${RED}❌ Go is not installed${NC}"
    echo "Please install Go 1.24.7+ from https://go.dev/dl/"
    exit 1
fi
echo -e "${GREEN}✅ Go $(go version | awk '{print $3}')${NC}"

# Check PostgreSQL
if ! command -v psql &> /dev/null; then
    echo -e "${YELLOW}⚠️  PostgreSQL client not found${NC}"
    echo "Install: brew install postgresql (macOS) or apt-get install postgresql (Linux)"
    exit 1
fi
echo -e "${GREEN}✅ PostgreSQL available${NC}"

# Check if postgres is running
if ! pg_isready &> /dev/null; then
    echo -e "${YELLOW}⚠️  PostgreSQL server not running${NC}"
    echo "Start it with: brew services start postgresql (macOS) or sudo service postgresql start (Linux)"
    exit 1
fi
echo -e "${GREEN}✅ PostgreSQL server running${NC}"

echo ""

# Database setup
echo "🗄️  Setting up database..."
DB_NAME="torrons"

# Ask for PostgreSQL credentials
read -p "PostgreSQL username [postgres]: " DB_USER
DB_USER=${DB_USER:-postgres}

read -sp "PostgreSQL password: " DB_PASSWORD
echo ""

# Test connection
if ! PGPASSWORD=$DB_PASSWORD psql -U $DB_USER -h localhost -lqt | cut -d \| -f 1 | grep -qw template1; then
    echo -e "${RED}❌ Failed to connect to PostgreSQL${NC}"
    echo "Please check your username and password"
    exit 1
fi
echo -e "${GREEN}✅ Connected to PostgreSQL${NC}"

# Create database if it doesn't exist
if PGPASSWORD=$DB_PASSWORD psql -U $DB_USER -h localhost -lqt | cut -d \| -f 1 | grep -qw $DB_NAME; then
    echo -e "${YELLOW}⚠️  Database '$DB_NAME' already exists${NC}"
    read -p "Drop and recreate? (y/N): " -n 1 -r
    echo ""
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        PGPASSWORD=$DB_PASSWORD psql -U $DB_USER -h localhost -c "DROP DATABASE $DB_NAME;" || true
        PGPASSWORD=$DB_PASSWORD psql -U $DB_USER -h localhost -c "CREATE DATABASE $DB_NAME;"
        echo -e "${GREEN}✅ Database recreated${NC}"
    fi
else
    PGPASSWORD=$DB_PASSWORD psql -U $DB_USER -h localhost -c "CREATE DATABASE $DB_NAME;"
    echo -e "${GREEN}✅ Database '$DB_NAME' created${NC}"
fi

echo ""

# Environment configuration
echo "⚙️  Configuring environment..."

if [ -f .env ]; then
    echo -e "${YELLOW}⚠️  .env file already exists${NC}"
    read -p "Overwrite? (y/N): " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Keeping existing .env file"
    else
        rm .env
    fi
fi

if [ ! -f .env ]; then
    cat > .env <<EOF
# Torrons Application Environment Variables
# Auto-generated by setup-local.sh

# Server Configuration
PORT=3000

# Database Configuration
DB_HOST=localhost
DB_PORT=5432
DB_USER=$DB_USER
DB_PASSWORD=$DB_PASSWORD
DB_NAME=$DB_NAME
DB_SSL_MODE=disable

# Logger Configuration
LOGGER_FORMAT=common
LOGGER_LEVEL=info
LOGGER_PATH=logs/torro.log
EOF
    echo -e "${GREEN}✅ .env file created${NC}"
else
    echo "Using existing .env file"
fi

echo ""
echo "================================="
echo -e "${GREEN}🎉 Setup Complete!${NC}"
echo ""
echo -e "${YELLOW}✨ Note: Migrations now run automatically on server startup!${NC}"
echo ""
echo "Next steps:"
echo "  1. Start the server (migrations will run automatically):"
echo "     ${GREEN}make run${NC}"
echo "     or"
echo "     ${GREEN}go run cmd/server/main.go${NC}"
echo ""
echo "  2. Open your browser:"
echo "     ${GREEN}http://localhost:3000${NC}"
echo ""
echo "  3. Test the features:"
echo "     See LOCAL_TESTING_GUIDE.md for complete testing checklist"
echo ""
echo "Optional: Run migrations manually with:"
echo "  ${GREEN}make migrate${NC}        - Run all pending migrations"
echo "  ${GREEN}make migrate-down${NC}   - Rollback last migration"
echo "  ${GREEN}make help${NC}           - See all available commands"
echo ""
echo "Happy testing! 🚀"
