insert into "Torrons"
    ("Id", "Name", "Image")
values
    (gen_random_uuid(), 'Chupa Chups de maduixa i nata', 'chupa_chups.jpg'),
    (gen_random_uuid(), 'Pernil Enric Tomàs', 'pernil.jpg'),
    (gen_random_uuid(), 'Mandarina i yuzu - Albert Adrià', 'mandarina_yuzu.jpg'),
    (gen_random_uuid(), 'Nata amb nous pecanes cantoneses - Albert Adrià', ',nata_nous.jpg'),
    (gen_random_uuid(), 'Lichi, gerds i roses', 'litxi_gerds_roses.jpg'),
    (gen_random_uuid(), 'Massapà de plàtan amb xocolata', 'mazapan_platan.jpg'),
    (gen_random_uuid(), 'Milfulles de maduixes amb nata', 'milfulls_maduixa.jpg'),
    (gen_random_uuid(), 'Praliné de coco amb dolç de pinya', 'praline_coco.jpg'),
    (gen_random_uuid(), 'Pur cacau', 'cacau_pur.jpg'),
    (gen_random_uuid(), 'Brownie amb nous pecanes - Solidari RAC1', 'brownie_nous.jpg'),
    (gen_random_uuid(), 'Donuts', 'donuts.jpg'),
    (gen_random_uuid(), 'Cremós de coco amb coco cruixent', 'cremos_coco.jpg'),
    (gen_random_uuid(), 'Mango, fruita de la passió i coco', 'mango_fruita_passio.jpg'),
    (gen_random_uuid(), 'Marrón glacé amb praliné de vainilla', 'marron_glace.jpg'),
    (gen_random_uuid(), 'Dulce de leche', 'dulce_leche.jpg'),
    (gen_random_uuid(), 'Cremós ametlla amb festuc a la sal', 'cremos_ametlla.jgp'),
    (gen_random_uuid(), 'Cremños ametlla amb macadamia caramelitzada i xocolate', 'cremos_ametlla_2.jpg'),
    (gen_random_uuid(), 'Festuc', 'festuc.jpg'),
    (gen_random_uuid(), 'Macadamia amb vainilla bourbon de madagascar i caramel salat', 'macadamia_bourbon.jpg'),
    (gen_random_uuid(), 'Mandarina amb praliné avellana', 'mandarina_praline.jpg'),
    (gen_random_uuid(), 'Massapà "Fruit explosion" - Tea Shop', 'fruit_explosion.jpg'),
    (gen_random_uuid(), 'Te negre "Christmas Tea" - Tea Shop', 'te_negre.jgp'),
    (gen_random_uuid(), 'Textures de llimona', 'textures_llimona.jpg'),
    (gen_random_uuid(), 'Vermut Miró', 'vermut.jpg'),
    (gen_random_uuid(), 'Polvoró amb canela', 'polvoro.jpg'),
    (gen_random_uuid(), 'Praliné de torró amb xocolata a la pedra', 'praline_torro.jpg'),
    (gen_random_uuid(), 'Galeta', 'galeta.jpg'),
    (gen_random_uuid(), 'Massapà music', 'music.jpg'),
    (gen_random_uuid(), 'Formatge, codonyat i nous', 'formatge.jpg'),
    (gen_random_uuid(), 'Ratafia amb nous', 'ratafia.jpg'),
    (gen_random_uuid(), 'Reus', 'reus.jpg'),
    (gen_random_uuid(), 'Baileys', 'baileys.jpg'),
    (gen_random_uuid(), 'Lays gourmet - Albert Adrià', 'lays.jpg'),
    (gen_random_uuid(), 'Cremós ametlla', 'cremos_ametlla_og.jpg'),
    (gen_random_uuid(), 'Màxim de fruites i massapà', 'maxim.jpg'),
    (gen_random_uuid(), 'Barcelona - Albert Adrià', 'barcelona.jpg'),
    (gen_random_uuid(), 'Cruixent de neules - Albert Adrià', 'neules.jpg'),
    (gen_random_uuid(), 'Festucs - Albert Adrià', 'festucs.jpg'),
    (gen_random_uuid(), 'Cherry Times - Albert Adrià', 'cherry.jpg'),
    (gen_random_uuid(), 'Café ristretto - Albert Adrià', 'cafe.jpg'),
    (gen_random_uuid(), 'Baklava - Albert Adrià', 'baklava.jpg'),
    (gen_random_uuid(), 'Taronja - Albert Adrià', 'taronja.jpg'),
    (gen_random_uuid(), 'Pa, oli i xocolate - Albert Adrià', 'pa.jpg'),
    (gen_random_uuid(), 'Cervesa - Albert Adrià', 'cervesa.jpg'),
    (gen_random_uuid(), 'Tiramisú - Albert Adrià', 'tiramisu.jpg'),
    (gen_random_uuid(), 'Gerds - Albert Adrià', 'gerds.jpg'),
    (gen_random_uuid(), 'Coco thai - Albert Adrià', 'thai.jpg'),
    (gen_random_uuid(), 'Tòfona blanca alba - Albert Adrià', 'trufa_blanca.jpg'),
    (gen_random_uuid(), 'Arròs amb llet - Albert Adrià', 'arros_llet.jpg'),
    (gen_random_uuid(), 'Vinagre i gerds - Albert Adrià', 'vinagre.jpg'),
    (gen_random_uuid(), 'Xocolata i xurros - Albert Adrià', 'xurros.jpg'),
    (gen_random_uuid(), 'Mojito - Albert Adrià', 'mojito.jpg'),
    (gen_random_uuid(), 'Pinya colada - Albert Adrià', 'colada.jpg'),
    (gen_random_uuid(), 'Curry i maduixa - Albert Adrià', 'curry.jpg'),
    (gen_random_uuid(), 'Pisada lunar - Albert Adrià', 'lunar.jpg'),
    (gen_random_uuid(), 'Kikos - Albert Adrià', 'kikos.jpg'),
    (gen_random_uuid(), 'Formatge de la Seu - Albert Adrià', 'seu.jpg'),
    (gen_random_uuid(), 'Arrels - Albert Adrià', 'arrels.jpg'),
    (gen_random_uuid(), 'Te matcha - Albert Adrià', 'matcha.jpg'),
    (gen_random_uuid(), 'Vi - Albert Adrià', 'vi.jpg'),
    (gen_random_uuid(), 'Pipes de carbassa - Albert Adrià', 'pipes.jpg'),
    (gen_random_uuid(), 'Mel i llimona - Albert Adrià', 'mel.jpg'),
    (gen_random_uuid(), 'Cheesecake - Albert Adrià', 'cheesecake.jpg'),
    (gen_random_uuid(), 'Pastís tatín - Albert Adrià', 'tatin.jpg'),
    (gen_random_uuid(), 'Aire- Albert Adrià', 'aire.jpg'),
    (gen_random_uuid(), 'Gintonic - Albert Adrià', 'gintonic.jpg'),
    (gen_random_uuid(), 'Tou cruixent', 'tou_cruixent.jpg'),
    (gen_random_uuid(), 'Xocolata amb llet i ametlla', 'xoco_llet.png'),
    (gen_random_uuid(), 'Xocolata amb llet i avellana', 'xoco_llet_2.png'),
    (gen_random_uuid(), 'Xocolate negra amb avellana', 'xoco_bitter.png'),
    (gen_random_uuid(), 'Xocolata negra a la sal', 'xoco_sal.jpg'),
    (gen_random_uuid(), 'Xocolata amb llet a la sal', 'xoco_sal_2.png'),
    (gen_random_uuid(), 'Xocolata negra cruixent', 'xoco_cruixent.png'),
    (gen_random_uuid(), 'Xocolata negra amb festuc', 'xoco_festuc.png'),
    (gen_random_uuid(), 'Xocolata amb llet i festuc', 'xoco_festuc_2.png'),
    (gen_random_uuid(), 'Xocolata blanca i festuc', 'xoco_festuc_3.png'),
    (gen_random_uuid(), 'Cruixent de iogurt i ametlla', 'iogurt.png'),
    (gen_random_uuid(), 'Cruixent de iogurt i coco', 'iogurt_coco.png'),
    (gen_random_uuid(), 'Xocolata blanca cruixent', 'blanca_cruixent.png'),
    (gen_random_uuid(), 'Xocolata amb llet cruixent', 'llet_cruixent.png'),
    (gen_random_uuid(), 'Trufa a la taronja', 'taronja.jpg'),
    (gen_random_uuid(), 'Trufa al brandy', 'brandy.png'),
    (gen_random_uuid(), 'Trufa al cafè', 'trufa_cafe.png'),
    (gen_random_uuid(), 'Trufa al marc de cava', 'trufa_cava.png'),
    (gen_random_uuid(), 'Trufa la whisky', 'trufa_whisky.png'),
    (gen_random_uuid(), 'Trufa amb guindes al licor', 'trufa_guindes.png'),
    (gen_random_uuid(), 'Iogurt amb nabius i papaia', 'iogurt_nabius.jpg'),
    (gen_random_uuid(), 'Iogurt amb festuc', 'iogurt_festuc.png'),
    (gen_random_uuid(), 'Picant "Brutal" - Marc Ribas', 'brutal.png'),
    (gen_random_uuid(), 'Crema cremada', 'crema_cremada.jpg'),
    (gen_random_uuid(), 'Coco', 'coco.jpg'),
    (gen_random_uuid(), 'Massapà fruita', 'fruita.jpg'),
    (gen_random_uuid(), 'Nata i nous', 'nata_nou.jpg'),
    (gen_random_uuid(), 'Crema cremada amb pinya', 'cremada_pinya.jpg'),
    (gen_random_uuid(), 'Crema cremada amb taronja', 'cremada_taronja.jpg'),
    (gen_random_uuid(), 'Coco xocolata', 'coco_xoco.jpg'),
    (gen_random_uuid(), 'Massapà amb cabell àngel', 'angel.jpg'),
    (gen_random_uuid(), 'Crema cremada amb cireres al Kirsch', 'cremada_cireres.jpg'),
    (gen_random_uuid(), 'Massapà amb xocolata', 'massapa_xocolata.jpg'),
    (gen_random_uuid(), 'Massapà amb praliné', 'massapa_praline.jpg'),
    (gen_random_uuid(), 'Massapà músic', 'massapa_music.jpg'),
    (gen_random_uuid(), 'Cremós de ratafia "Brutal" - Marc Ribas', 'brutal_2.jpg'),
    (gen_random_uuid(), 'Crema a la canyella', 'canyella.jpg'),
    (gen_random_uuid(), 'Crema cremada al ron cremat', 'cremada_ron.jpg'),
    (gen_random_uuid(), 'Crema amb brownie', 'crema_brownie.jpg'),
    (gen_random_uuid(), 'Cruixent de coco amb xocolata', 'coco_cruixent.jpg'),
    (gen_random_uuid(), 'Crema cremada al ron cremat', 'cremada_ron.jpg'),
    (gen_random_uuid(), 'Dur ametlla', 'dur.jpg'),
    (gen_random_uuid(), 'Tou ametlla', 'tou.jpg')
