insert into "Torrons"
    ("Id", "Name", "Image", "Class")
values
    -- Albert Adrià
    (gen_random_uuid(), 'Mandarina i yuzu - Albert Adrià', 'mandarina_yuzu.jpg', '4'),
    (gen_random_uuid(), 'Nata amb nous pecanes cantoneses - Albert Adrià', 'nata_nous.jpg', '4'),
    (gen_random_uuid(), 'Lays gourmet - Albert Adrià', 'lays.jpg', '4'),
    (gen_random_uuid(), 'Barcelona - Albert Adrià', 'barcelona.jpg', '4'),
    (gen_random_uuid(), 'Cruixent de neules - Albert Adrià', 'neules.jpg', '4'),
    (gen_random_uuid(), 'Festucs - Albert Adrià', 'festucs.jpg', '4'),
    (gen_random_uuid(), 'Cherry Times - Albert Adrià', 'cherry.jpg', '4'),
    (gen_random_uuid(), 'Café ristretto - Albert Adrià', 'cafe.jpg', '4'),
    (gen_random_uuid(), 'Baklava - Albert Adrià', 'baklava.jpeg', '4'),
    (gen_random_uuid(), 'Taronja - Albert Adrià', 'taronja.jpg', '4'),
    (gen_random_uuid(), 'Pa, oli i xocolata - Albert Adrià', 'pa.jpg', '4'),
    (gen_random_uuid(), 'Cervesa - Albert Adrià', 'cervesa.jpg', '4'),
    (gen_random_uuid(), 'Tiramisú - Albert Adrià', 'tiramisu.jpg', '4'),
    (gen_random_uuid(), 'Gerds - Albert Adrià', 'gerds.jpg', '4'),
    (gen_random_uuid(), 'Coco thai - Albert Adrià', 'thai.jpg', '4'),
    (gen_random_uuid(), 'Tòfona blanca alba - Albert Adrià', 'trufa_blanca.jpg', '4'),
    (gen_random_uuid(), 'Arròs amb llet - Albert Adrià', 'arros_llet.jpg', '4'),
    (gen_random_uuid(), 'Vinagre i gerds - Albert Adrià', 'vinagre.jpg', '4'),
    (gen_random_uuid(), 'Xocolata i xurros - Albert Adrià', 'xurros.jpg', '4'),
    (gen_random_uuid(), 'Mojito - Albert Adrià', 'mojito.jpg', '4'),
    (gen_random_uuid(), 'Pinya colada - Albert Adrià', 'colada.jpg', '4'),
    (gen_random_uuid(), 'Curry i maduixa - Albert Adrià', 'curry.jpg', '4'),
    (gen_random_uuid(), 'Petjada lunar - Albert Adrià', 'lunar.jpg', '4'),
    (gen_random_uuid(), 'Kikos - Albert Adrià', 'kikos.jpg', '4'),
    (gen_random_uuid(), 'Formatge de la Seu - Albert Adrià', 'seu.jpg', '4'),
    (gen_random_uuid(), 'Arrels - Albert Adrià', 'arrels.jpg', '4'),
    (gen_random_uuid(), 'Te matcha - Albert Adrià', 'matcha.jpg', '4'),
    (gen_random_uuid(), 'Vi - Albert Adrià', 'vi.jpg', '4'),
    (gen_random_uuid(), 'Pipes de carbassa - Albert Adrià', 'pipes.jpg', '4'),
    (gen_random_uuid(), 'Mel i llimona - Albert Adrià', 'mel.jpg', '4'),
    (gen_random_uuid(), 'Pastís de formatge - Albert Adrià', 'cheesecake.jpg', '4'),
    (gen_random_uuid(), 'Pastís tatín - Albert Adrià', 'tatin.jpg', '4'),
    (gen_random_uuid(), 'Aire - Albert Adrià', 'aire.jpg', '4'),
    (gen_random_uuid(), 'Gintonic - Albert Adrià', 'gintonic.jpg', '4'),

    -- Nous
    (gen_random_uuid(), 'Chupa Chups de maduixa i nata', 'chupa_chups.jpg', '2'),
    (gen_random_uuid(), 'Pernil Enrique Tomàs', 'pernil.jpg', '2'),
    (gen_random_uuid(), 'Lichi, gerds i roses', 'litxi_gerds_roses.jpg', '2'),
    (gen_random_uuid(), 'Massapà de plàtan amb xocolata', 'mazapan_platan.jpg', '2'),
    (gen_random_uuid(), 'Milfulles de maduixes amb nata', 'milfulls_maduixa.jpg', '2'),
    (gen_random_uuid(), 'Praliné de coco amb dolç de pinya', 'praline_coco.jpg', '2'),
    (gen_random_uuid(), 'Pur cacau', 'cacau_pur.jpg', '2'),
    (gen_random_uuid(), 'Brownie amb nous pecanes - Solidari RAC1', 'brownie_nous.jpg', '2'),
    (gen_random_uuid(), 'Donuts', 'donuts.jpg', '2'),
    (gen_random_uuid(), 'Cremós de coco amb coco cruixent', 'cremos_coco.jpg', '2'),
    (gen_random_uuid(), 'Mango, fruita de la passió i coco', 'mango_fruita_passio.jpg', '2'),
    (gen_random_uuid(), 'Marrón glacé amb praliné de vainilla', 'marron_glace.jpg', '2'),
    (gen_random_uuid(), 'Dulce de leche', 'dulce_leche.jpg', '2'),
    (gen_random_uuid(), 'Cremós ametlla amb festuc a la sal', 'cremos_ametlla.jgp', '2'),
    (gen_random_uuid(), 'Cremós ametlla amb macadamia caramelitzada i xocolata', 'cremos_ametlla_2.jpg', '2'),
    (gen_random_uuid(), 'Festuc', 'festuc.jpg', '2'),
    (gen_random_uuid(), 'Macadamia amb vainilla bourbon de madagascar i caramel salat', 'macadamia_bourbon.jpg', '2'),
    (gen_random_uuid(), 'Mandarina amb praliné avellana', 'mandarina_praline.jpg', '2'),
    (gen_random_uuid(), 'Massapà "Fruit explosion" - Tea Shop', 'fruit_explosion.jpg', '2'),
    (gen_random_uuid(), 'Te negre "Christmas Tea" - Tea Shop', 'te_negre.jgp', '2'),
    (gen_random_uuid(), 'Textures de llimona', 'textures_llimona.jpg', '2'),
    (gen_random_uuid(), 'Vermut Miró', 'vermut.jpg', '2'),
    (gen_random_uuid(), 'Polvoró amb canela', 'polvoro.jpg', '2'),
    (gen_random_uuid(), 'Praliné de torró amb xocolata a la pedra', 'praline_torro.jpg', '2'),
    (gen_random_uuid(), 'Galeta', 'galeta.jpg', '2'),
    (gen_random_uuid(), 'Massapà music', 'music.jpg', '2'),
    (gen_random_uuid(), 'Formatge, codonyat i nous', 'formatge.jpg', '2'),
    (gen_random_uuid(), 'Ratafia amb nous', 'ratafia.jpg', '2'),
    (gen_random_uuid(), 'Reus', 'reus.jpg', '2'),
    (gen_random_uuid(), 'Baileys', 'baileys.jpg', '2'),
    (gen_random_uuid(), 'Cremós ametlla', 'cremos_ametlla_og.jpg', '2'),
    (gen_random_uuid(), 'Màxim de fruites i massapà', 'maxim.jpg', '2'),
    (gen_random_uuid(), 'Cruixent de iogurt i ametlla', 'iogurt.png', '2'),
    (gen_random_uuid(), 'Cruixent de iogurt i coco', 'iogurt_coco.png', '2'),
    (gen_random_uuid(), 'Trufa a la taronja', 'taronja.jpg', '2'),
    (gen_random_uuid(), 'Trufa al brandy', 'brandy.png', '2'),
    (gen_random_uuid(), 'Trufa al cafè', 'trufa_cafe.png', '2'),
    (gen_random_uuid(), 'Trufa al marc de cava', 'trufa_cava.png', '2'),
    (gen_random_uuid(), 'Trufa la whisky', 'trufa_whisky.png', '2'),
    (gen_random_uuid(), 'Trufa amb guindes al licor', 'trufa_guindes.png', '2'),
    (gen_random_uuid(), 'Iogurt amb nabius i papaia', 'iogurt_nabius.jpg', '2'),
    (gen_random_uuid(), 'Iogurt amb festuc', 'iogurt_festuc.png', '2'),
    (gen_random_uuid(), 'Picant "Brutal" - Marc Ribas', 'brutal.png', '2'),

    -- Clàssics
    (gen_random_uuid(), 'Tou cruixent', 'tou_cruixent.jpg', '2'),
    (gen_random_uuid(), 'Crema cremada', 'crema_cremada.jpg', '2'),
    (gen_random_uuid(), 'Coco', 'coco.jpg', '2'),
    (gen_random_uuid(), 'Massapà fruita', 'fruita.jpg', '2'),
    (gen_random_uuid(), 'Nata i nous', 'nata_nou.jpg', '2'),
    (gen_random_uuid(), 'Crema cremada amb pinya', 'cremada_pinya.jpg', '2'),
    (gen_random_uuid(), 'Crema cremada amb taronja', 'cremada_taronja.jpg', '2'),
    (gen_random_uuid(), 'Coco xocolata', 'coco_xoco.jpg', '2'),
    (gen_random_uuid(), 'Dur ametlla', 'dur.jpg', '2'),
    (gen_random_uuid(), 'Tou ametlla', 'tou.jpg', '2'),
    (gen_random_uuid(), 'Massapà amb cabell àngel', 'angel.jpg', '2'),
    (gen_random_uuid(), 'Crema cremada amb cireres al Kirsch', 'cremada_cireres.jpg', '2'),
    (gen_random_uuid(), 'Massapà amb xocolata', 'massapa_xocolata.jpg', '2'),
    (gen_random_uuid(), 'Massapà amb praliné', 'massapa_praline.jpg', '2'),
    (gen_random_uuid(), 'Massapà músic', 'massapa_music.jpg', '2'),
    (gen_random_uuid(), 'Cremós de ratafia "Brutal" - Marc Ribas', 'brutal_2.jpg', '2'),
    (gen_random_uuid(), 'Crema a la canyella', 'canyella.jpg', '2'),
    (gen_random_uuid(), 'Crema cremada al ron cremat', 'cremada_ron.jpg', '2'),
    (gen_random_uuid(), 'Crema amb brownie', 'crema_brownie.jpg', '2'),

    -- Xocolata
    (gen_random_uuid(), 'Xocolata amb llet i ametlla', 'xoco_llet.png', '3'),
    (gen_random_uuid(), 'Xocolata amb llet i avellana', 'xoco_llet_2.png', '3'),
    (gen_random_uuid(), 'Xocolate negra amb avellana', 'xoco_bitter.png', '3'),
    (gen_random_uuid(), 'Xocolata negra a la sal', 'xoco_sal.png', '3'),
    (gen_random_uuid(), 'Xocolata amb llet a la sal', 'xoco_sal_2.jpg', '3'),
    (gen_random_uuid(), 'Xocolata negra cruixent', 'xoco_cruixent.png', '3'),
    (gen_random_uuid(), 'Xocolata negra amb festuc', 'xoco_festuc.png', '3'),
    (gen_random_uuid(), 'Xocolata amb llet i festuc', 'xoco_festuc_2.png', '3'),
    (gen_random_uuid(), 'Xocolata blanca i festuc', 'xoco_festuc_3.png', '3'),
    (gen_random_uuid(), 'Xocolata blanca cruixent', 'blanca_cruixent.png', '3'),
    (gen_random_uuid(), 'Xocolata amb llet cruixent', 'llet_cruixent.png', '3'),
    (gen_random_uuid(), 'Cruixent de coco amb xocolata', 'coco_cruixent.jpg', '3')


