  name: build and publish image 
  on: 
    push:
      tags:
        - '*'
  jobs:
     build-and-push:
       runs-on: ubuntu-latest 
       steps:
       - name: code checkout 
         uses: actions/checkout@v4
       - name: qemu setup 
         uses: docker/setup-qemu-action@v3
       - name: build image 
         uses: docker/setup-buildx-action@v3
       - name: login to container repo 
         uses: docker/login-action@v3
         with:
           registry: ghcr.io
           username: ${{ github.repository_owner }}
           password: ${{ secrets.GITHUB_TOKEN }}
       - name: extract metadata 
         id: md 
         uses: docker/metadata-action@v5
         with:
          images: ghcr.io/${{ github.repository }}
       - name: build and push  
         uses: docker/build-push-action@v5
         with:
           context: .
           platforms: linux/amd64,linux/arm64
           push: true
           tags: ${{ steps.md.outputs.tags }}
           labels: ${{ steps.md.outputs.labels}}
